### ISSUE TITLE
Please change the F3 message

### ISSUE THREAD

**Issue by jr8ppg** [w7sst/MorseRunner#381] opened 2024-11-30 09:31 UTC
## Tell us about your experience.
Feedback from JA users.

* In CQWW, there was a station that only sent "TU" after a QSO.
* Currently the F3 message is "TU".
* So I suggest changing ”TU" to "TU \<my\>".
* If you change the message, it will be the same as the real contest.
* I think it will be a good example for beginners.

**Comment by w7sst** [comment] 2024-12-12 02:51
This is a duplicate of Issue #247.

**Closed by w7sst** 2024-12-12 02:51 UTC
Labels: duplicate, feedback
